package com.undefined.quasar.interfaces.entities.entity.decoration

interface Painting : HangingEntity {

    fun setVariant(variant: Variant)
    fun getVariant(): Variant

    enum class Variant(val key: String) {
        KEBAB("kebab"),
        AZTEC("aztec"),
        ALBAN("alban"),
        AZTEC2("aztec2"),
        BOMB("bomb"),
        PLANT("plant"),
        WASTELAND("wasteland"),
        POOL("pool"),
        COURBET("courbet"),
        SEA("sea"),
        SUNSET("sunset"),
        CREEBET("creebet"),
        WANDERER("wanderer"),
        GRAHAM("graham"),
        MATCH("match"),
        BUST("bust"),
        STAGE("stage"),
        VOID("void"),
        SKULL_AND_ROSES("skull_and_roses"),
        WITHER("wither"),
        FIGHTERS("fighters"),
        POINTER("pointer"),
        PIGSCENE("pigscene"),
        BURNING_SKULL("burning_skull"),
        SKELETON("skeleton"),
        DONKEY_KONG("donkey_kong"),
        EARTH("earth"),
        WIND("wind"),
        WATER("water"),
        FIRE("fire"),
        BAROQUE("baroque"),
        HUMBLE("humble"),
        MEDITATIVE("meditative"),
        PRAIRIE_RIDE("prairie_ride"),
        UNPACKED("unpacked"),
        BACKYARD("backyard"),
        BOUQUET("bouquet"),
        CAVEBIRD("cavebird"),
        CHANGING("changing"),
        COTAN("cotan"),
        ENDBOSS("endboss"),
        FERN("fern"),
        FINDING("finding"),
        LOWMIST("lowmist"),
        ORB("orb"),
        OWLEMONS("owlemons"),
        PASSAGE("passage"),
        POND("pond"),
        SUNFLOWERS("sunflowers"),
        TIDES("tides")
    }
}